apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  # TODO: write your code here
 replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: sql-pass
            key: password
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql
